// Code generated by Wire. DO NOT EDIT.

//go:generate go run github.com/google/wire/cmd/wire
//+build !wireinject

package token

import (
	"context"
	"github.com/bobvawter/cacheroach/pkg/store/cdc"
	"github.com/bobvawter/cacheroach/pkg/store/principal"
	"github.com/bobvawter/cacheroach/pkg/store/storetesting"
	"github.com/bobvawter/cacheroach/pkg/store/tenant"
)

// Injectors from test_rig.go:

func testRig(ctx context.Context) (*rig, func(), error) {
	config, err := storetesting.ProvideStoreConfig()
	if err != nil {
		return nil, nil, err
	}
	logger := _wireLoggerValue
	pool, cleanup, err := storetesting.ProvideDB(ctx, config, logger)
	if err != nil {
		return nil, nil, err
	}
	notifier := cdc.ProvideNotifier(pool, logger)
	server, cleanup2, err := ProvideServer(ctx, config, pool, logger, notifier)
	if err != nil {
		cleanup()
		return nil, nil, err
	}
	tenantServer := &tenant.Server{
		DB:     pool,
		Logger: logger,
	}
	principalServer := &principal.Server{
		Config: config,
		DB:     pool,
		Logger: logger,
	}
	tokenRig := &rig{
		tokens:     server,
		tenants:    tenantServer,
		principals: principalServer,
	}
	return tokenRig, func() {
		cleanup2()
		cleanup()
	}, nil
}

var (
	_wireLoggerValue = storetesting.Logger
)

// test_rig.go:

type rig struct {
	tokens     *Server
	tenants    *tenant.Server
	principals *principal.Server
}
