// Code generated by Wire. DO NOT EDIT.

//go:generate go run github.com/google/wire/cmd/wire
//+build !wireinject

package cdc

import (
	"context"
	"github.com/bobvawter/cacheroach/pkg/store/storetesting"
	"github.com/jackc/pgx/v4/pgxpool"
)

// Injectors from test_rig.go:

func testRig(ctx context.Context) (*rig, func(), error) {
	config, err := storetesting.ProvideStoreConfig()
	if err != nil {
		return nil, nil, err
	}
	logger := _wireLoggerValue
	pool, cleanup, err := storetesting.ProvideDB(ctx, config, logger)
	if err != nil {
		return nil, nil, err
	}
	notifier := ProvideNotifier(pool, logger)
	cdcRig := &rig{
		db:       pool,
		notifier: notifier,
	}
	return cdcRig, func() {
		cleanup()
	}, nil
}

var (
	_wireLoggerValue = storetesting.Logger
)

// test_rig.go:

type rig struct {
	db       *pgxpool.Pool
	notifier *Notifier
}
