// Code generated by Wire. DO NOT EDIT.

//go:generate go run github.com/google/wire/cmd/wire
//+build !wireinject

package cache

import (
	"context"
	"github.com/Mandala/go-log"
	"github.com/bobvawter/cacheroach/pkg/metrics"
	"github.com/prometheus/client_golang/prometheus"
)

// Injectors from test_rig.go:

func testRig(ctx context.Context, cfg *Config, logger *log.Logger) (*rig, func(), error) {
	registry := prometheus.NewPedanticRegistry()
	factory := metrics.ProvideFactory(registry)
	cache, cleanup, err := ProvideCache(ctx, factory, cfg, logger)
	if err != nil {
		return nil, nil, err
	}
	cacheRig := &rig{
		Cache: cache,
	}
	return cacheRig, func() {
		cleanup()
	}, nil
}

// test_rig.go:

type rig struct {
	*Cache
}
