// Code generated by Wire. DO NOT EDIT.

//go:generate go run github.com/google/wire/cmd/wire
//+build !wireinject

package tenant

import (
	"context"
	"github.com/bobvawter/cacheroach/pkg/store/storetesting"
)

// Injectors from test_rig.go:

func newForTesting(ctx context.Context) (*Server, func(), error) {
	config, err := storetesting.ProvideStoreConfig()
	if err != nil {
		return nil, nil, err
	}
	logger := _wireLoggerValue
	pool, cleanup, err := storetesting.ProvideDB(ctx, config, logger)
	if err != nil {
		return nil, nil, err
	}
	server := &Server{
		DB:     pool,
		Logger: logger,
	}
	return server, func() {
		cleanup()
	}, nil
}

var (
	_wireLoggerValue = storetesting.Logger
)
