// Code generated by Wire. DO NOT EDIT.

//go:generate go run github.com/google/wire/cmd/wire
//+build !wireinject

package upload

import (
	"context"
	"github.com/bobvawter/cacheroach/pkg/cache"
	"github.com/bobvawter/cacheroach/pkg/store/blob"
	"github.com/bobvawter/cacheroach/pkg/store/fs"
	"github.com/bobvawter/cacheroach/pkg/store/principal"
	"github.com/bobvawter/cacheroach/pkg/store/storetesting"
	"github.com/bobvawter/cacheroach/pkg/store/tenant"
	"github.com/bobvawter/cacheroach/pkg/store/token"
)

// Injectors from test_rig.go:

func testRig(ctx context.Context) (*rig, func(), error) {
	config, cleanup, err := storetesting.ProvideCacheConfig()
	if err != nil {
		return nil, nil, err
	}
	logger := _wireLoggerValue
	cacheCache, cleanup2, err := cache.ProvideCache(ctx, config, logger)
	if err != nil {
		cleanup()
		return nil, nil, err
	}
	configConfig, err := storetesting.ProvideStoreConfig()
	if err != nil {
		cleanup2()
		cleanup()
		return nil, nil, err
	}
	pool, cleanup3, err := storetesting.ProvideDB(ctx, configConfig, logger)
	if err != nil {
		cleanup2()
		cleanup()
		return nil, nil, err
	}
	store, cleanup4 := blob.ProvideStore(ctx, cacheCache, configConfig, pool, logger)
	fsStore, cleanup5, err := fs.ProvideStore(ctx, store, configConfig, pool, logger)
	if err != nil {
		cleanup4()
		cleanup3()
		cleanup2()
		cleanup()
		return nil, nil, err
	}
	server, err := ProvideServer(store, configConfig, pool, fsStore, logger)
	if err != nil {
		cleanup5()
		cleanup4()
		cleanup3()
		cleanup2()
		cleanup()
		return nil, nil, err
	}
	principalServer := &principal.Server{
		Config: configConfig,
		DB:     pool,
		Logger: logger,
	}
	tenantServer := &tenant.Server{
		DB:     pool,
		Logger: logger,
	}
	tokenServer, err := token.ProvideServer(configConfig, pool, logger)
	if err != nil {
		cleanup5()
		cleanup4()
		cleanup3()
		cleanup2()
		cleanup()
		return nil, nil, err
	}
	uploadRig := &rig{
		uploads:    server,
		fs:         fsStore,
		principals: principalServer,
		tenants:    tenantServer,
		tokens:     tokenServer,
	}
	return uploadRig, func() {
		cleanup5()
		cleanup4()
		cleanup3()
		cleanup2()
		cleanup()
	}, nil
}

var (
	_wireLoggerValue = storetesting.Logger
)

// test_rig.go:

type rig struct {
	uploads    *Server
	fs         *fs.Store
	principals *principal.Server
	tenants    *tenant.Server
	tokens     *token.Server
}
