// Code generated by Wire. DO NOT EDIT.

//go:generate go run github.com/google/wire/cmd/wire
//+build !wireinject

package auth

import (
	"context"
	"github.com/bobvawter/cacheroach/pkg/store/principal"
	"github.com/bobvawter/cacheroach/pkg/store/storetesting"
	"github.com/bobvawter/cacheroach/pkg/store/token"
)

// Injectors from test_rig.go:

func testRig(ctx context.Context) (*rig, func(), error) {
	config, err := storetesting.ProvideStoreConfig()
	if err != nil {
		return nil, nil, err
	}
	logger := _wireLoggerValue
	pool, cleanup, err := storetesting.ProvideDB(ctx, config, logger)
	if err != nil {
		return nil, nil, err
	}
	server := &principal.Server{
		Config: config,
		DB:     pool,
		Logger: logger,
	}
	tokenServer, err := token.ProvideServer(config, pool, logger)
	if err != nil {
		cleanup()
		return nil, nil, err
	}
	authServer := &Server{
		Config:     config,
		DB:         pool,
		Principals: server,
		Tokens:     tokenServer,
	}
	authRig := &rig{
		auth:       authServer,
		principals: server,
	}
	return authRig, func() {
		cleanup()
	}, nil
}

var (
	_wireLoggerValue = storetesting.Logger
)

// test_rig.go:

type rig struct {
	auth       *Server
	principals *principal.Server
}
