// Code generated by Wire. DO NOT EDIT.

//go:generate go run github.com/google/wire/cmd/wire
//+build !wireinject

package vhost

import (
	"context"
	"github.com/bobvawter/cacheroach/pkg/store/principal"
	"github.com/bobvawter/cacheroach/pkg/store/storetesting"
	"github.com/bobvawter/cacheroach/pkg/store/tenant"
)

// Injectors from test_rig.go:

func testRig(ctx context.Context) (*rig, func(), error) {
	config, err := storetesting.ProvideStoreConfig()
	if err != nil {
		return nil, nil, err
	}
	logger := _wireLoggerValue
	pool, cleanup, err := storetesting.ProvideDB(ctx, config, logger)
	if err != nil {
		return nil, nil, err
	}
	server := &Server{
		DB:     pool,
		Logger: logger,
	}
	principalServer := &principal.Server{
		Config: config,
		DB:     pool,
		Logger: logger,
	}
	tenantServer := &tenant.Server{
		DB:     pool,
		Logger: logger,
	}
	vhostRig := &rig{
		vhosts:     server,
		principals: principalServer,
		tenants:    tenantServer,
	}
	return vhostRig, func() {
		cleanup()
	}, nil
}

var (
	_wireLoggerValue = storetesting.Logger
)

// test_rig.go:

type rig struct {
	vhosts     *Server
	principals *principal.Server
	tenants    *tenant.Server
}
